### ISSUE TITLE
call error, possibly related to #376

### ISSUE THREAD

**Issue by ghost** [alecgorge/jsonapi#380]
I am still getting these errors with the latest version of JSONAPI #110 and Spigot #1551

[10:59:39 WARN]: java.lang.NoSuchFieldException: length
[10:59:39 WARN]:        at java.lang.Class.getDeclaredField(Class.java:1948)
[10:59:39 WARN]:        at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[10:59:39 WARN]:        at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[10:59:39 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[10:59:39 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[10:59:39 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:638)
[10:59:39 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[10:59:39 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[10:59:39 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[10:59:39 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[10:59:41 WARN]: java.lang.NoSuchFieldException: length
[10:59:41 WARN]:        at java.lang.Class.getDeclaredField(Class.java:1948)
[10:59:41 WARN]:        at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[10:59:41 WARN]:        at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[10:59:41 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[10:59:41 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[10:59:41 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:638)
[10:59:41 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[10:59:41 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[10:59:41 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[10:59:41 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by nullschritt** [comment]
Even with the latest builds I get this error, and in order to fix it I have to delete my methods, why is this happening?

**Comment by alecgorge** [comment]
Because the APIs changed. It used to be that online players were stored in array (and the number of line players accessed with getOnlinePlayers().length), now it is a collection and should be accessed like this getOnlinePlayer().size(). If you are still getting this error, it means you are using the ancient v1 API. This API is going away soon and you should move to the v2 API

**Comment by nullschritt** [comment]
Sorry for sounding like a noob, but you're saying that my php scripts need to use a newer version of the api, and that how the number of online players is collected has changed?

**Comment by nullschritt** [comment]
This is my current PHP Code.

$players = $api->call("players.online.count", array(''));
$online = $players[0]['success'];

Is this still correct, assuming I update my api?

**Comment by alecgorge** [comment]
Hmm...that all looks fine but deleting your methods.json shouldn't have made any difference. Are you running Spigot 1.8?

**Comment by nullschritt** [comment]
No I'm running the last build of spigot 1.7.9

Right after I delete the methods the script functions normally, then somewhere along the line during another restart, it starts giving me these errors again and wont return the number of players online properly. The only solution I currently have is having my restart script delete the methods on each startup....

**Comment by nullschritt** [comment]
Okay, I'm full of crap apparently. Now it doesn't matter what I do, I get this length error every time I try to query the number of players online.

**Comment by nullschritt** [comment]
I even tried updating the methods file to change .length to .size() but I still get the .length error in console. >.<

**Comment by nullschritt** [comment]
Okay, I resolved my issue by going to the jenkins, getting build 111, for 1.7.9 (non-snapshot version), and then erasing all methods and allowing a clean restart.

**Comment by SyMbR4x** [comment]
cgkgk;l
