### ISSUE TITLE
Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by Jckf** [alecgorge/jsonapi#408]
```
[21:53:54] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling Minecraftno v1.7.10-R0.1-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:115) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:98) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at com.alecgorge.minecraft.jsonapi.adminium.Adminium3.sendNotification(Adminium3.java:98) ~[?:?]
    at com.alecgorge.minecraft.jsonapi.adminium.Adminium3.pushNotification(Adminium3.java:65) ~[?:?]
    at com.alecgorge.minecraft.jsonapi.adminium.Adminium3$ConsoleHandler.publish(Adminium3.java:185) ~[?:?]
    at java.util.logging.Logger.log(Logger.java:616) [?:1.7.0_65]
    at java.util.logging.Logger.doLog(Logger.java:641) [?:1.7.0_65]
    at java.util.logging.Logger.log(Logger.java:730) [?:1.7.0_65]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:358) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:431) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:412) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:393) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
```

**Comment by alecgorge** [comment]
Probably should fix this, but it is harmless I believe
