### ISSUE TITLE
Player count and players list seem don't work

### ISSUE THREAD

**Issue by JohOply** [alecgorge/jsonapi#413]
Hi

On my website, I can't see how many players are connected, but not each times. Sometimes, after restart, there isn't any problem. I use JSONAPI 5.6.0 - 1.7.9-R0.2 ; Spigot 1.7.10-R0.2-b1656

When there is the problem, I have one frequent error :

[00:11:47 WARN]: java.lang.NoSuchFieldException: length
[00:11:47 WARN]: at java.lang.Class.getDeclaredField(Class.java:1948)
[00:11:47 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[00:11:47 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
[00:11:47 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[00:11:47 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[00:11:47 WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[00:11:47 WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[00:11:47 WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[00:11:47 WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[00:11:47 WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by alecgorge** [comment]
This should be fixed in the latest builds.

New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.
