### ISSUE TITLE
JSONAPI 1.8

### ISSUE THREAD

**Issue by Raphy123** [alecgorge/jsonapi#418]
Hi :)

Spigot 1.8 is released. JSONAPI can't load on my server.. he will be release ? :)

Thanks

**Comment by frdmn** [comment]
Can't get the latest build loaded with Spigot b1649:

    [17:58:00] [Server thread/ERROR]: Could not load 'plugins/JSONAPI_5.6.0-FOR18.jar' in folder 'plugins'
    org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: io/netty/channel/SimpleChannelInboundHandler
      at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:341) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:263) [spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot-1.8-b1649.jar:git-Spigot-1649]
      at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8-b1649.jar:git-Spigot-1649]
      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.8-b1649.jar:git-Spigot-1649]
      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.8-b1649.jar:git-Spigot-1649]
    Caused by: java.lang.NoClassDefFoundError: io/netty/channel/SimpleChannelInboundHandler
      at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_65]
      at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_65]
      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_65]
      at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_65]
      at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_65]
      at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_65]
      at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_65]
      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_65]
      at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
      at com.alecgorge.minecraft.jsonapi.JSONAPI.<init>(JSONAPI.java:102) ~[?:?]
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
      at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
      at java.lang.Class.newInstance(Class.java:379) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      ... 6 more
    Caused by: java.lang.ClassNotFoundException: io.netty.channel.SimpleChannelInboundHandler
      at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_65]
      at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_65]
      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_65]
      at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
      at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_65]
      at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_65]
      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_65]
      at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_65]
      at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_65]
      at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_65]
      at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_65]
      at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_65]
      at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
      at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
      at com.alecgorge.minecraft.jsonapi.JSONAPI.<init>(JSONAPI.java:102) ~[?:?]
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
      at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
      at java.lang.Class.newInstance(Class.java:379) ~[?:1.7.0_65]
      at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.8-b1649.jar:git-Spigot-1649]
      ... 6 more

Any ideas?

**Comment by krisdb2009** [comment]
Not sure if you have spigots ProtocolLib or not. But if you don't try it out. http://www.spigotmc.org/resources/protocollib.1997/

**Comment by frdmn** [comment]
@krisdb2009 Thanks a ton! That was exactly my issue! Works now :)

**Comment by krisdb2009** [comment]
@frdmn I'm glad to help.

**Comment by alecgorge** [comment]
New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.

**Comment by alecgorge** [comment]
Please see #426 if you would like to discuss new features and open an issue for new bugs
