### ISSUE TITLE
How open to file with JSONAPI in read-only ?

### ISSUE THREAD

**Issue by fabien91** [alecgorge/jsonapi#428]
Hello,

I've tried this method : fs.read.
but my file is open on my website and can't close with an other method ?
I would open a file essentials (userdata) but when it is open, i've an error with essentials

[16:52:31] [Server thread/INFO]: fabien91 issued server command: /god
java.io.FileNotFoundException: C:\Users\Fabien\Desktop\Serveur 1.8\plugins\Essentials\userdata\UUID.yml (L’opération demandée n’a pu s’accomplir sur un fichier ayant une section mappée utilisateur ouverte)
	at java.io.FileOutputStream.open(Native Method) ~[?:1.8.0_31]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_31]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_31]
	at com.earth2me.essentials.EssentialsConf$WriteRunner.run(EssentialsConf.java:415) [Essentials-2.x-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_31]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

Essentials don't write in his file :/

How to open a file in read-only please with JSONAPI ?

**Comment by electronicboy** [comment]
Not supported, windows will automatically lock a file when it's opened with java, only way is for additional libraries to be included with the plugin to allow talking with the windows API to unlock the file but that won't work too well and would leave to cases where a file is read after it's been opened yet not unlocked yet.

This issue doesn't/won't exist on Linux which doesn't force file locks (they're supported, but they're only advisory, an application can just ignore the lock if it's programmed to, or listen to the lock and not touch it as programmed)

**Comment by fabien91** [comment]
Ok, I've find the solution, I use fopen and fclose with PHP for read my files and it's perfect ;)

**Comment by lifehome** [comment]
@fabien91 May you please kindly close this issue if it is resolved?
