### ISSUE TITLE
1.8.3 - Issues

### ISSUE THREAD

**Issue by krisdb2009** [alecgorge/jsonapi#431]
players.name Only works for players Online, If offline it throws an exception.
chat.with_name Only works if the player is Online, It also throws an exception.
I'm not sure about other things.

The GSON library has been moved in Spigot 1.8.3 if any imports may be broken.

**Comment by lifehome** [comment]
Could you put the exception/errorlog up here via gist?

This would be a great help on us debugging the whole thing.

**Comment by krisdb2009** [comment]
[16:49:30] [Thread-177/WARN]: java.lang.reflect.InvocationTargetException
[16:49:30] [Thread-177/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:49:30] [Thread-177/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:49:30] [Thread-177/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:49:30] [Thread-177/WARN]: at java.lang.reflect.Method.invoke(Method.java:483)
[16:49:30] [Thread-177/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:170)
[16:49:30] [Thread-177/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[16:49:30] [Thread-177/WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftFuture.run(CraftFuture.java:89)
[16:49:30] [Thread-177/WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:49:30] [Thread-177/WARN]: at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718)
[16:49:30] [Thread-177/WARN]: at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[16:49:30] [Thread-177/WARN]: at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[16:49:30] [Thread-177/WARN]: at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[16:49:30] [Thread-177/WARN]: at java.lang.Thread.run(Thread.java:745)
[16:49:30] [Thread-177/WARN]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/MinecraftServer
[16:49:30] [Thread-177/WARN]: at com.alecgorge.minecraft.jsonapi.JSONAPI.loadOfflinePlayer(JSONAPI.java:859)
[16:49:30] [Thread-177/WARN]: at com.alecgorge.minecraft.jsonapi.chat.BukkitRealisticChat.chatWithName(BukkitRealisticChat.java:25)
[16:49:30] [Thread-177/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.chatWithName(APIWrapperMethods.java:498)
[16:49:30] [Thread-177/WARN]: ... 13 more
[16:49:30] [Thread-177/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.MinecraftServer
[16:49:30] [Thread-177/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[16:49:30] [Thread-177/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:49:30] [Thread-177/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:49:30] [Thread-177/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:49:30] [Thread-177/WARN]: ... 16 more
[16:49:48] [Thread-197/WARN]: java.lang.reflect.InvocationTargetException
[16:49:48] [Thread-197/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:49:48] [Thread-197/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:49:48] [Thread-197/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:49:48] [Thread-197/WARN]: at java.lang.reflect.Method.invoke(Method.java:483)
[16:49:48] [Thread-197/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:170)
[16:49:48] [Thread-197/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[16:49:48] [Thread-197/WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftFuture.run(CraftFuture.java:89)
[16:49:48] [Thread-197/WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:49:48] [Thread-197/WARN]: at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718)
[16:49:48] [Thread-197/WARN]: at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[16:49:48] [Thread-197/WARN]: at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[16:49:48] [Thread-197/WARN]: at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[16:49:48] [Thread-197/WARN]: at java.lang.Thread.run(Thread.java:745)
[16:49:48] [Thread-197/WARN]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/MinecraftServer
[16:49:48] [Thread-197/WARN]: at com.alecgorge.minecraft.jsonapi.JSONAPI.loadOfflinePlayer(JSONAPI.java:859)
[16:49:48] [Thread-197/WARN]: at com.alecgorge.minecraft.jsonapi.chat.BukkitRealisticChat.chatWithName(BukkitRealisticChat.java:25)
[16:49:48] [Thread-197/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.chatWithName(APIWrapperMethods.java:498)
[16:49:48] [Thread-197/WARN]: ... 13 more
[16:49:48] [Thread-197/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.MinecraftServer
[16:49:48] [Thread-197/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[16:49:48] [Thread-197/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:49:48] [Thread-197/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:49:48] [Thread-197/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:49:48] [Thread-197/WARN]: ... 16 more

**Comment by dodekeract** [comment]
Having issues with 1.8.3 too:
[04:03:14 WARN]: Exception in thread "Thread-316"
[04:03:14 WARN]: Exception in thread "Thread-317"
[04:03:14 WARN]: java.lang.NullPointerException
[04:03:14 WARN]:        at java.util.LinkedList$ListItr.next(LinkedList.java:893)
[04:03:14 WARN]:        at com.google.common.collect.Iterators$9.next(Iterators.java:939)
[04:03:14 WARN]:        at com.google.common.collect.Iterators.addAll(Iterators.java:357)
[04:03:14 WARN]:        at com.google.common.collect.Lists.newArrayList(Lists.java:147)
[04:03:14 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.a(SourceFile:189)
[04:03:14 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.c(SourceFile:173)
[04:03:14 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.getProfile(SourceFile:120)
[04:03:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftProfileBanList.isBanned(CraftProfileBanList.java:84)
[04:03:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.isBanned(CraftPlayer.java:721)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.stringifier.BukkitStringifier.handle(BukkitStringifier.java:130)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:217)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:214)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:104)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:86)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:93)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:208)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:98)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.call(APIv2Handler.java:86)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.serve(APIv2Handler.java:51)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.JSONServer.serve(JSONServer.java:266)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:553)
[04:03:14 WARN]:        at java.lang.Thread.run(Thread.java:745)
[04:03:14 WARN]: java.lang.NullPointerException
[04:03:14 WARN]:        at java.util.LinkedList$ListItr.next(LinkedList.java:893)
[04:03:14 WARN]:        at com.google.common.collect.Iterators$9.next(Iterators.java:939)
[04:03:14 WARN]:        at com.google.common.collect.Iterators.addAll(Iterators.java:357)
[04:03:14 WARN]:        at com.google.common.collect.Lists.newArrayList(Lists.java:147)
[04:03:14 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.a(SourceFile:189)
[04:03:14 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.c(SourceFile:173)
[04:03:14 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.getProfile(SourceFile:120)
[04:03:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftProfileBanList.isBanned(CraftProfileBanList.java:84)
[04:03:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.isBanned(CraftPlayer.java:721)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.stringifier.BukkitStringifier.handle(BukkitStringifier.java:130)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:217)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:214)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:104)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:86)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:93)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:208)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[04:03:14 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:98)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.call(APIv2Handler.java:86)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.serve(APIv2Handler.java:51)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.JSONServer.serve(JSONServer.java:266)
[04:03:14 WARN]:        at com.alecgorge.minecraft.jsonapi.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:553)
[04:03:14 WARN]:        at java.lang.Thread.run(Thread.java:745)

[I left out some repetitive ones]

[04:03:50 WARN]: Exception in thread "Thread-350"
[04:03:50 WARN]: java.lang.NullPointerException
[04:03:50 WARN]: Exception in thread "Thread-349"
[04:03:50 WARN]: java.lang.NullPointerException
[04:03:50 WARN]: java.lang.NullPointerException
[04:03:56 WARN]: Exception in thread "Thread-351"
[04:03:56 WARN]: java.lang.NullPointerException
[04:03:56 WARN]: Exception in thread "Thread-353"
[04:03:56 WARN]: java.lang.NullPointerException
[04:03:56 WARN]: Exception in thread "Thread-352"
[04:03:56 WARN]: java.util.ConcurrentModificationException
[04:03:56 WARN]:        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
[04:03:56 WARN]:        at java.util.LinkedList$ListItr.next(LinkedList.java:888)
[04:03:56 WARN]:        at com.google.common.collect.Iterators$9.next(Iterators.java:939)
[04:03:56 WARN]:        at com.google.common.collect.Iterators.addAll(Iterators.java:357)
[04:03:56 WARN]:        at com.google.common.collect.Lists.newArrayList(Lists.java:147)
[04:03:56 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.a(SourceFile:189)
[04:03:56 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.c(SourceFile:173)
[04:03:56 WARN]:        at net.minecraft.server.v1_8_R2.UserCache.getProfile(SourceFile:120)
[04:03:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftProfileBanList.isBanned(CraftProfileBanList.java:84)
[04:03:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.isBanned(CraftPlayer.java:721)
[04:03:56 WARN]:        at com.alecgorge.minecraft.jsonapi.stringifier.BukkitStringifier.handle(BukkitStringifier.java:130)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:217)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:214)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:104)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:86)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:93)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:208)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[04:03:56 WARN]:        at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:98)
[04:03:56 WARN]:        at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.call(APIv2Handler.java:86)
[04:03:56 WARN]:        at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.serve(APIv2Handler.java:51)
[04:03:56 WARN]:        at com.alecgorge.minecraft.jsonapi.JSONServer.serve(JSONServer.java:266)
[04:03:56 WARN]:        at com.alecgorge.minecraft.jsonapi.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:553)
[04:03:56 WARN]:        at java.lang.Thread.run(Thread.java:745)
[04:04:01 WARN]: Exception in thread "Thread-354"
[04:04:01 WARN]: java.lang.NullPointerException
[04:04:01 WARN]: Exception in thread "Thread-356"
[04:04:01 WARN]: java.lang.NullPointerException
[04:04:01 WARN]: Exception in thread "Thread-355"
[04:04:01 WARN]: java.lang.NullPointerException
[04:04:06 WARN]: Exception in thread "Thread-357"
[04:04:06 WARN]: java.lang.NullPointerException
[04:04:06 WARN]: Exception in thread "Thread-359"
[04:04:06 WARN]: Exception in thread "Thread-358"
[04:04:06 WARN]: java.lang.NullPointerException
[04:04:06 WARN]: java.lang.NullPointerException
[04:04:08 WARN]: Exception in thread "Thread-360"
[04:04:08 WARN]: java.lang.NullPointerException
[04:04:08 WARN]: Exception in thread "Thread-361"
[04:04:08 WARN]: java.lang.NullPointerException
[04:04:08 WARN]: Exception in thread "Thread-362"
[04:04:08 WARN]: java.lang.NullPointerException
[04:04:10 WARN]: Exception in thread "Thread-363"
[04:04:10 WARN]: java.lang.NullPointerException
[04:04:10 WARN]: Exception in thread "Thread-364"
[04:04:10 WARN]: java.lang.NullPointerException
[04:04:10 WARN]: Exception in thread "Thread-365"
[04:04:10 WARN]: java.lang.NullPointerException
[04:04:14 INFO]: Dodekeract lost connection: Disconnected
[04:04:14 INFO]: [dynmap] Full/radius render pause set to false
[04:04:14 INFO]: [dynmap] Resume full/radius renders - below player limit
[04:04:14 INFO]: Dodekeract left the game.

**Comment by lifehome** [comment]
@krisdb2009  @dodekeract 
Please edit your comment and use gist.github.com instead of pasting all these logs here.
