### ISSUE TITLE
java.net.ProtocolException: Server redirected too many times (20)

### ISSUE THREAD

**Issue by JohOply** [alecgorge/jsonapi#440]
Hi

I use latest version of JSONAPI, and even if there isn't any request sent to the server, an error spam my logs :

[19:26:07 WARN]: java.net.ProtocolException: Server redirected too many times (20)
[19:26:07 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1636)
[19:26:07 WARN]: at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
[19:26:07 WARN]: at com.alecgorge.java.http.MutableHttpRequest.request(MutableHttpRequest.java:186)
[19:26:07 WARN]: at com.alecgorge.java.http.MutableHttpRequest.post(MutableHttpRequest.java:204)
[19:26:07 WARN]: at com.alecgorge.minecraft.jsonapi.api.StreamPusher$1.run(StreamPusher.java:147)
[19:26:07 WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
[19:26:07 WARN]: at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:26:07 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[19:26:07 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[19:26:07 WARN]: at java.lang.Thread.run(Thread.java:744)

Could you do something to fix it please ? :)

Thanks in advance

**Comment by JohOply** [comment]
I have also this error : 

[07:48:25 WARN]: java.lang.NoSuchFieldException: length
[07:48:25 WARN]: at java.lang.Class.getDeclaredField(Class.java:1948)
[07:48:25 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[07:48:25 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[07:48:25 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
[07:48:25 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[07:48:25 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
[07:48:25 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[07:48:25 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[07:48:25 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[07:48:25 WARN]: at java.lang.Thread.run(Thread.java:744)
