### ISSUE TITLE
Websockets and SSLHandshakeException ??

### ISSUE THREAD

**Issue by atheleron** [alecgorge/jsonapi#443]
Im running Spigot 1.8.7 with:
- ProtocolLib v3.6.3-SNAPSHOT
- Vault v1.5.3-b37
- JSONAPI v5.6.0

It all runs fine with Adminium and i just love it but now I'm trying to make website using jsonapi-v2.js without node.js just Websockets and [Vue.js](http://vuejs.org) but something is wrong with websocket connection the server is now running locally on osx but after will be moved to ubuntu server online

```WebSocket connection to 'ws://localhost:20061/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED```

I get connection refused not sure is related but in console there is warning about SSL so how i can fix those ??

```
[10:22:31 INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[10:22:31 INFO]: [JSONAPI] Remote Toolkit cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[10:22:31 INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[10:22:31 INFO]: [JSONAPI] Remote Toolkit methods cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[10:22:31 INFO]: [JSONAPI] 384 methods loaded in 7 namespaces.
[10:22:31 INFO]: [JSONAPI] ------[Connection information]-------
[10:22:31 INFO]: [JSONAPI] JSON Server listening on 20059
[10:22:31 INFO]: [JSONAPI] JSON Stream Server listening on 20060
[10:22:31 INFO]: [JSONAPI] JSON WebSocket Stream Server listening on 20061
[10:22:31 INFO]: [JSONAPI] Active and listening for requests.
[10:22:31 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[10:22:31 WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[10:22:31 WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
[10:22:31 WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[10:22:31 WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[10:22:31 WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
[10:22:31 WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[10:22:31 WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[10:22:31 WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[10:22:31 WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
[10:22:31 WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
[10:22:31 WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
[10:22:31 WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
[10:22:31 WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[10:22:31 WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[10:22:31 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[10:22:31 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
[10:22:31 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[10:22:31 WARN]: 	at java.net.URL.openStream(URL.java:1038)
[10:22:31 WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130)
[10:22:31 WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108)
[10:22:31 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[10:22:31 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[10:22:31 WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[10:22:31 WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:230)
[10:22:31 WARN]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[10:22:31 WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[10:22:31 WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[10:22:31 WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[10:22:31 WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
[10:22:31 WARN]: 	... 16 more
[10:22:31 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[10:22:31 WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[10:22:31 WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[10:22:31 WARN]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[10:22:31 WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[10:22:31 WARN]: 	... 22 more
[10:22:31 INFO]: [JSONAPI] -------------------------------------
```

**Comment by alecgorge** [comment]
try connecting the websocket with `ws://localhost:25565/api/2/websocket`

that error is unrelated and it means your java certificate store is out of date

**Comment by Quentin-M** [comment]
Maybe 'cause you are using a certificate allocated for *.alecgorge.com on mcjsonapi.com ?
That is absolutely incorrect.

**Comment by electronicboy** [comment]
Plugin doesn't create a connection to that website...
The issue is most likely at the stage where it connects to https://tools.alecgorge.com/ip.php to grab the public IP address. issue is on the users install environment, not in the plugin. (updating the ca certificates file would solve this issue)

**Comment by THEDanielCF** [comment]
I'm having a similar problem here's my last startup console log.
[22:10:58 INFO]: Starting minecraft server version 1.8
[22:10:58 INFO]: Loading properties
[22:10:58 INFO]: Default game type: SURVIVAL
[22:10:58 INFO]: Generating keypair
[22:10:58 INFO]: Starting Minecraft server on 162.248.93.164:25565
[22:10:58 INFO]: This server is running CraftBukkit version git-Bukkit-ee6d0fa (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[22:10:59 INFO]: [GroupManager] Loading GroupManager v2.1.31 (Phoenix)
[22:10:59 INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id
[22:10:59 INFO]: [CoreProtect] Loading CoreProtect v2.11.2
[22:10:59 INFO]: [NBTEditor] Loading NBTEditor v1.2
[22:10:59 INFO]: [OpenInv] Loading OpenInv v2.2.9
[22:10:59 INFO]: [Vault] Loading Vault v1.5.3-b37
[22:10:59 INFO]: [ProtocolLib] Loading ProtocolLib v3.6.3-SNAPSHOT-b142
[22:10:59 INFO]: [JSONAPI] Loading JSONAPI v5.6.0
[22:10:59 INFO]: [RedProtect] Loading RedProtect v5.4.1
[22:10:59 INFO]: [TreeAssist] Loading TreeAssist v5.8.89
[22:10:59 INFO]: [WorldGuard] Loading WorldGuard v6.1
[22:10:59 INFO]: [Essentials] Loading Essentials vTeamCity
[22:10:59 INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.0.1-b154
[22:10:59 INFO]: [EssentialsGeoIP] Loading EssentialsGeoIP vTeamCity
[22:10:59 INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[22:10:59 INFO]: [WorldEditSelectionVisualizer] Loading WorldEditSelectionVisualizer v1.4.2
[22:10:59 INFO]: [Vault] Enabling Vault v1.5.3-b37
[22:10:59 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[22:10:59 INFO]: [Vault] [Permission] GroupManager found: Waiting
[22:10:59 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[22:10:59 INFO]: [Vault] [Chat] GroupManager found: Waiting
[22:10:59 INFO]: [Vault] Enabled Version 1.5.3-b37
[22:10:59 INFO]: [ProtocolLib] Enabling ProtocolLib v3.6.3-SNAPSHOT-b142
[22:10:59 INFO]: [ProtocolLib] Started structure compiler thread.
[22:10:59 INFO]: Preparing level "Ice"
[22:10:59 INFO]: Preparing start region for level 0 (Seed: 85490543201)
[22:11:00 INFO]: Preparing spawn area: 51%
[22:11:01 INFO]: Preparing start region for level 1 (Seed: 85490543201)
[22:11:02 INFO]: Preparing spawn area: 58%
[22:11:02 INFO]: [GroupManager] Enabling GroupManager v2.1.31 (Phoenix)
[22:11:02 INFO]: GroupManager - INFO - World Found: ice
[22:11:02 INFO]: GroupManager - INFO - World Found: world
[22:11:02 INFO]: GroupManager - INFO - World Found: test
[22:11:02 INFO]: GroupManager - INFO - Superperms support enabled.
[22:11:02 INFO]: GroupManager - INFO - Scheduled Data Saving is set for every 10 minutes!
[22:11:02 INFO]: GroupManager - INFO - Backups will be retained for 24 hours!
[22:11:02 INFO]: GroupManager version 2.1.31 (Phoenix) is enabled!
[22:11:02 INFO]: [Vault][Permission] GroupManager hooked.
[22:11:02 INFO]: [Vault][Chat] GroupManager - Chat hooked.
[22:11:02 INFO]: [WorldEdit] Enabling WorldEdit v6.1;no_git_id
[22:11:03 INFO]: WEPIF: GroupManager detected! Using GroupManager for permissions.
[22:11:03 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[22:11:03 INFO]: [CoreProtect] Enabling CoreProtect v2.11.2
[22:11:03 INFO]: CoreProtect version 2.11.2 is enabled!
[22:11:03 INFO]: [CoreProtect] Using SQLite for data storage.
[22:11:03 INFO]: [NBTEditor] Enabling NBTEditor v1.2
[22:11:04 INFO]: [CustomItemsAPI] CustomItemManager initialized.
[22:11:04 INFO]: [NBTEditor] NBTEditor has been enabled.
[22:11:04 INFO]: [OpenInv] Enabling OpenInv v2.2.9
[22:11:04 INFO]: [JSONAPI] Enabling JSONAPI v5.6.0
[22:11:04 INFO]: [JSONAPI] Logging to file: false
[22:11:04 INFO]: [JSONAPI] Logging to console: true
[22:11:04 INFO]: [JSONAPI] IP Whitelist = None, all requests are allowed.
[22:11:04 INFO]: [JSONAPI] Loaded methods.json.
[22:11:04 INFO]: [JSONAPI] Waiting 2.000 seconds to load methods so that all the other plugins load...
[22:11:04 INFO]: [JSONAPI] Any requests in this time will not work...
[22:11:06 INFO]: [JSONAPI] Attempting to use port 20059
[22:11:06 INFO]: [RedProtect] Enabling RedProtect v5.4.1
[22:11:06 INFO]: Redprotect: [All configurations loaded!]
[22:11:06 INFO]: Redprotect: [Language file loaded - Using: EN-US]
[22:11:06 INFO]: Redprotect: [Creating a new data fileplugins/RedProtect//data/data_Ice_nether.backup]
[22:11:06 INFO]: Redprotect: [Data file is blank, Reading from plugins/RedProtect//data/data_Ice_nether.backup]
[22:11:06 INFO]: Redprotect: [Creating a new data fileplugins/RedProtect//data/data_Ice_the_end.backup]
[22:11:06 INFO]: Redprotect: [Data file is blank, Reading from plugins/RedProtect//data/data_Ice_the_end.backup]
[22:11:06 INFO]: Redprotect: [Loaded 13 regions (yml)]
[22:11:06 INFO]: Redprotect: [RedProtect v5.4.1 enabled.]
[22:11:06 INFO]: Redprotect: [Checking for update...]
[22:11:06 INFO]: Redprotect: [No update available.]
[22:11:06 INFO]: Redprotect: [Auto-save Scheduler: Saving yml database every 20 minutes!]
[22:11:06 INFO]: [TreeAssist] Enabling TreeAssist v5.8.89
[22:11:06 INFO]: [TreeAssist] debugging: off
[22:11:06 INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[22:11:06 INFO]: [JSONAPI] Remote Toolkit cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[22:11:06 INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[22:11:06 INFO]: [JSONAPI] Remote Toolkit methods cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[22:11:06 INFO]: [JSONAPI] 384 methods loaded in 7 namespaces.
[22:11:06 INFO]: [JSONAPI] ------[Connection information]-------
[22:11:06 INFO]: [JSONAPI] JSON Server listening on 20059
[22:11:06 INFO]: [JSONAPI] JSON Stream Server listening on 20060
[22:11:06 INFO]: [JSONAPI] JSON WebSocket Stream Server listening on 20061
[22:11:06 INFO]: [JSONAPI] Active and listening for requests.
[22:11:06 INFO]: [WorldGuard] Enabling WorldGuard v6.1
[22:11:07 INFO]: [WorldGuard] (Ice) TNT ignition is PERMITTED.
[22:11:07 INFO]: [WorldGuard] (Ice) Lighters are PERMITTED.
[22:11:07 INFO]: [WorldGuard] (Ice) Lava fire is blocked.
[22:11:07 INFO]: [WorldGuard] (Ice) Fire spread is UNRESTRICTED.
[22:11:07 INFO]: [WorldGuard] Loaded configuration for world 'Ice'
[22:11:07 INFO]: [WorldGuard] (Ice_nether) TNT ignition is PERMITTED.
[22:11:07 INFO]: [WorldGuard] (Ice_nether) Lighters are PERMITTED.
[22:11:07 INFO]: [WorldGuard] (Ice_nether) Lava fire is blocked.
[22:11:07 INFO]: [WorldGuard] (Ice_nether) Fire spread is UNRESTRICTED.
[22:11:07 INFO]: [WorldGuard] Loaded configuration for world 'Ice_nether'
[22:11:07 INFO]: [WorldGuard] (Ice_the_end) TNT ignition is PERMITTED.
[22:11:07 INFO]: [WorldGuard] (Ice_the_end) Lighters are PERMITTED.
[22:11:07 INFO]: [WorldGuard] (Ice_the_end) Lava fire is blocked.
[22:11:07 INFO]: [WorldGuard] (Ice_the_end) Fire spread is UNRESTRICTED.
[22:11:07 INFO]: [WorldGuard] Loaded configuration for world 'Ice_the_end'
[22:11:07 INFO]: [WorldGuard] Loading region data...
[22:11:07 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[22:11:07 WARN]: at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.Handshaker.process_record(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[22:11:07 WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[22:11:07 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[22:11:07 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[22:11:07 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[22:11:07 WARN]: at java.net.URL.openStream(Unknown Source)
[22:11:07 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130)
[22:11:07 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108)
[22:11:07 WARN]: at java.lang.Thread.run(Unknown Source)
[22:11:07 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[22:11:07 WARN]: at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[22:11:07 WARN]: at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[22:11:07 WARN]: at sun.security.validator.Validator.validate(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[22:11:07 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[22:11:07 WARN]: ... 16 more
[22:11:07 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[22:11:07 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[22:11:07 WARN]: at java.security.cert.CertPathBuilder.build(Unknown Source)
[22:11:07 WARN]: ... 22 more
[22:11:07 INFO]: [JSONAPI] -------------------------------------
[22:11:07 INFO]: [Essentials] Enabling Essentials vTeamCity
[22:11:07 WARN]: ?4Version mismatch! Please update EssentialsSpawn to the same version.
[22:11:07 INFO]: Bukkit version format changed. Version not checked.
[22:11:07 INFO]: git-Bukkit-ee6d0fa (MC: 1.8)
[22:11:07 INFO]: 1.8-R0.1-SNAPSHOT
[22:11:07 INFO]: Using locale en_US
[22:11:07 INFO]: Using locale en_US
[22:11:07 INFO]: [Vault][Economy] Essentials Economy hooked.
[22:11:07 INFO]: Essentials: Using GroupManager based permissions.
[22:11:07 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b154
[22:11:07 WARN]: ?4Version mismatch! Please update all Essentials jars to the same version.
[22:11:07 INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP vTeamCity
[22:11:07 INFO]: [EssentialsGeoIP] This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com/.
[22:11:07 INFO]: [EssentialsChat] Enabling EssentialsChat vTeamCity
[22:11:07 INFO]: [WorldEditSelectionVisualizer] Enabling WorldEditSelectionVisualizer v1.4.2
[22:11:07 INFO]: Server permissions file [] is empty, ignoring it
[22:11:08 INFO]: Done (8.317s)! For help, type "help" or "?"
[22:11:08 INFO]: Starting GS4 status listener
[22:11:08 INFO]: Query running on 162.248.93.164:25565
[22:11:08 INFO]: GroupManager - INFO - Bukkit Permissions Updated!
[22:11:08 INFO]: [Vault] Checking for Updates ... 
[22:11:08 INFO]: CONSOLE issued server command: /list 
[22:11:08 INFO]: There are 0 out of maximum 24 players online.
[22:11:08 INFO]: [Vault] No new version available

**Comment by alecgorge** [comment]
> issue is on the users install environment, not in the plugin. (updating the ca certificates file would solve this issue)

^ this

**Comment by divad** [comment]
I have the latest Java cacerts file in the latest Java 8 and I'm still getting this error. Are you sure the problem is at our end?

**Comment by electronicboy** [comment]
See #442
Oracle removed SHA1 CA root certificates, technically the issue is in the user environment, however this could be resolved JSON-API side by getting a cert which doesn't use certificates signed by a SHA1 root

**Comment by divad** [comment]
Technically its most definitely not client side. SHA1 is deprecated and jsonapi should not repeat should NOT be using them! 

https://konklone.com/post/why-google-is-hurrying-the-web-to-kill-sha-1

Oracle removing SHA-1 to me says you need to switch to SHA2 certs.
