### ISSUE TITLE
Issue with Validator

### ISSUE THREAD

**Issue by mythseur** [alecgorge/jsonapi#444]
Hi everyone !

I have a probleme when i start my server with JSONAPI 

[15:10:24] [Thread-12/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1446)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:837)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
[15:10:24] [Thread-12/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[15:10:24] [Thread-12/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[15:10:24] [Thread-12/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
[15:10:24] [Thread-12/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[15:10:24] [Thread-12/WARN]: 	at java.net.URL.openStream(URL.java:1037)
[15:10:24] [Thread-12/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130)
[15:10:24] [Thread-12/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108)
[15:10:24] [Thread-12/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:10:24] [Thread-12/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[15:10:24] [Thread-12/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
[15:10:24] [Thread-12/WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:230)
[15:10:24] [Thread-12/WARN]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
[15:10:24] [Thread-12/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1428)
[15:10:24] [Thread-12/WARN]: 	... 15 more
[15:10:24] [Thread-12/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[15:10:24] [Thread-12/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
[15:10:24] [Thread-12/WARN]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
[15:10:24] [Thread-12/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
[15:10:24] [Thread-12/WARN]: 	... 21 more
[15:10:24] [Thread-12/INFO]: [JSONAPI] -------------------------------------

I don't understand what is the probleme and can't find a solution on the web.

Can you please help me.

Thanks

Mythseur

**Comment by krisdb2009** [comment]
Read this issue: https://github.com/alecgorge/jsonapi/issues/443

**Comment by spkane** [comment]
As pointed out by electronicboy in #443 this will workaround this issue:

Downlaod and save the pem file on this support page:

https://support.comodo.com/index.php?/Knowledgebase/Article/View/970/0/intermediate-2-sha-2-comodo-rsa-domain-validation-secure-server-ca

Download and save the cert on this support page:

https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/917/91/

On Linux run something like this:
```
# sudo /usr/java/latest/bin/keytool -importcert -file ~/Downloads/comodo-domain-cert.pem -keystore /usr/java/latest/jre/lib/security/cacerts -alias comododomain
# sudo /usr/java/latest/bin/keytool -importcert -file ~/Downloads/addtrustexternalcaroot.crt -keystore /usr/java/latest/jre/lib/security/cacerts -alias addtrustexternalcaroot
```
The default keystore password is *changeit*

If keytool tells you that the addtrustexternalcaroot is already in your keystore, then you do not need to add it, and can cancel.

**Comment by R3d0x5704** [comment]
Anyone  has a solution to solve  this issue  without  add the  CA-cert ? 

I don't have a dedicated server  , so  I can't  test  this solution. 
Need help.. 

Thx
