### ISSUE TITLE
how I get rid of the [Thread-23/WARN]-ings

### ISSUE THREAD

**Issue by THEDanielCF** [alecgorge/jsonapi#446]
[12:18:02] [Thread-23/INFO]: [JSONAPI] 388 methods loaded in 8 namespaces.
[12:18:02] [Thread-23/INFO]: [JSONAPI] ------[Connection information]-------
[12:18:02] [Thread-23/INFO]: [JSONAPI] JSON Server listening on 20059
[12:18:02] [Thread-23/INFO]: [JSONAPI] JSON Stream Server listening on 20060
[12:18:02] [Thread-23/INFO]: [JSONAPI] JSON WebSocket Stream Server listening on 20061
[12:18:02] [Thread-23/INFO]: [JSONAPI] Active and listening for requests.
[12:18:03] [Thread-23/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.Handshaker.process_record(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at java.net.URL.openStream(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130)
[12:18:03] [Thread-23/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108)
[12:18:03] [Thread-23/WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:18:03] [Thread-23/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[12:18:03] [Thread-23/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.validator.Validator.validate(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	... 16 more
[12:18:03] [Thread-23/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[12:18:03] [Thread-23/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	at java.security.cert.CertPathBuilder.build(Unknown Source)
[12:18:03] [Thread-23/WARN]: 	... 22 more
[12:18:03] [Thread-23/INFO]: [JSONAPI] -------------------------------------

**Comment by electronicboy** [comment]
#442 See comment down the page
