### ISSUE TITLE
Error when server start

### ISSUE THREAD

**Issue by JohOply** [alecgorge/jsonapi#447]
Hi,

I use Spigot 1.8.7-b500 and JSONAPI 5.6.0 for 1.8 and i have an error when server start : 

[13:40:04 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[13:40:04 WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[13:40:04 WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
[13:40:04 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
[13:40:04 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
[13:40:04 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
[13:40:04 WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
[13:40:04 WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
[13:40:04 WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
[13:40:04 WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
[13:40:04 WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
[13:40:04 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
[13:40:04 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
[13:40:04 WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[13:40:04 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[13:40:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
[13:40:04 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[13:40:04 WARN]: at java.net.URL.openStream(URL.java:1037)
[13:40:04 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130)
[13:40:04 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108)
[13:40:04 WARN]: at java.lang.Thread.run(Thread.java:744)
[13:40:04 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[13:40:04 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
[13:40:04 WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:230)
[13:40:04 WARN]: at sun.security.validator.Validator.validate(Validator.java:260)
[13:40:04 WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
[13:40:04 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[13:40:04 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
[13:40:04 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323)
[13:40:04 WARN]: ... 15 more
[13:40:04 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[13:40:04 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
[13:40:04 WARN]: at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
[13:40:04 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
[13:40:04 WARN]: ... 21 more

Could you fix it please ? :)

**Comment by electronicboy** [comment]
See: #442
