### ISSUE TITLE
Essentials error and ideas for next update

### ISSUE THREAD

**Issue by Alextronick** [alecgorge/jsonapi#450]
Hello,

i have JSONAPI.jar and Essentials.jar instaled on my server. When i call any method of essentials ("essentials.reload") i have an error on the web page and on the console.

In index.php :
![capture](https://cloud.githubusercontent.com/assets/13223514/8552842/e726bb78-24df-11e5-917e-7e94d249ab60.PNG)

Error in web page :
![capture2](https://cloud.githubusercontent.com/assets/13223514/8552854/f6f3c456-24df-11e5-92e7-f4501e3c4161.PNG)

Error in console :
![capture3](https://cloud.githubusercontent.com/assets/13223514/8552866/019134a2-24e0-11e5-8342-28de5116f4e1.PNG)

For the next update if you can add the UUID in the player informations (online and offline) ??

Thanks for read my post.

Good, Great and Usefull plugin ever, CONTINUE !!!

Best regards,
Alextronick.

**Comment by Kushhh** [comment]
have you tried server.run_command alternative ? 
$UUID = $api->call("server.run_command, array("reload"));

idk what the essentials.reload call is doing but you should try this and teel us if it works.

**Comment by kmonagle** [comment]
Any thoughts on this? I'm having an identical issue...the essentials calls are all failing with the following error:

[22:14:05 INFO]: [JSONAPI] [API Request] admin requested: essentials.config.get_keys([]){AUTHED, ALLOWED} 
[22:14:05 WARN]: java.lang.reflect.InvocationTargetException
[22:14:05 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:14:05 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:14:05 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:14:05 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[22:14:05 WARN]: 	at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:52)
[22:14:05 WARN]: 	at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[22:14:05 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
[22:14:05 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:14:05 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[22:14:05 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:14:05 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[22:14:05 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[22:14:05 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:14:05 WARN]: Caused by: java.lang.NullPointerException
[22:14:05 WARN]: 	at com.alecgorge.minecraft.jsonapi.api.v2.EssentialsAPIMethods.get_configuration(EssentialsAPIMethods.java:36)
[22:14:05 WARN]: 	... 13 more
[22:23:15 INFO]: [JSONAPI] [API Request] admin requested: essentials.config.get_keys([]){AUTHED, ALLOWED} 
[22:23:15 WARN]: java.lang.reflect.InvocationTargetException
[22:23:15 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:23:15 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:23:15 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:23:15 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[22:23:15 WARN]: 	at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:52)
[22:23:15 WARN]: 	at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[22:23:15 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftFuture.run(CraftFuture.java:89)
[22:23:15 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:23:15 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[22:23:15 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:23:15 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[22:23:15 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[22:23:15 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:23:15 WARN]: Caused by: java.lang.NullPointerException
[22:23:15 WARN]: 	at com.alecgorge.minecraft.jsonapi.api.v2.EssentialsAPIMethods.get_configuration(EssentialsAPIMethods.java:36)
[22:23:15 WARN]: 	... 13 more
