### ISSUE TITLE
Error SSL : last build not working

### ISSUE THREAD

**Issue by R3d0x5704** [alecgorge/jsonapi#451]
Hello , I open a new topic to see more clearly . Indeed, for several days, JSONAPI longer works whatever the version.

The problem from the SHA1 certificate Oracle.

A solution has been proposed is to change the certificate on the JVM. However, if the players do not have access, as did they do? Would it be possible to have a final build where the problem is corrected ?

Thank you in advance

Community French Bukkit

_______________________

Error : 
[14:29:27] [Thread-28/INFO]: [JSONAPI] Active and listening for requests.
[14:29:27] [Thread-28/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1836)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1337)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:154)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:966)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1262)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1289)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1273)
[14:29:27] [Thread-28/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:523)
[14:29:27] [Thread-28/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[14:29:27] [Thread-28/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1296)
[14:29:27] [Thread-28/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[14:29:27] [Thread-28/WARN]: 	at java.net.URL.openStream(URL.java:1035)
[14:29:27] [Thread-28/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:131)
[14:29:27] [Thread-28/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:109)
[14:29:27] [Thread-28/WARN]: 	at java.lang.Thread.run(Thread.java:722)
[14:29:27] [Thread-28/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[14:29:27] [Thread-28/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
[14:29:27] [Thread-28/WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[14:29:27] [Thread-28/WARN]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
[14:29:27] [Thread-28/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1319)
[14:29:27] [Thread-28/WARN]: 	... 15 more
[14:29:27] [Thread-28/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[14:29:27] [Thread-28/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
[14:29:27] [Thread-28/WARN]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
[14:29:27] [Thread-28/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
[14:29:27] [Thread-28/WARN]: 	... 21 more
[14:29:27] [Thread-28/INFO]: [JSONAPI] -------------------------------------

**Comment by HeyAwesomePeople** [comment]
I am getting this issue too. It doesn't seem to be affecting anything but every solution I have tried to come across is for a server system. I'm on Windows 7, and cannot run those commands...

I don't know much about internet security and these certificates, but could the deprecated SHA1 implementation of certificate security in JSONAPI be causing any issues?

**Comment by Trsak** [comment]
Hi, there, same issue here:
[08:06:46 INFO]: [JSONAPI] Active and listening for requests. 
> [08:06:46 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
> [08:06:46 WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) 
> [08:06:46 WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937) 
> [08:06:46 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) 
> [08:06:46 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) 
> [08:06:46 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) 
> [08:06:46 WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
> [08:06:46 WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) 
> [08:06:46 WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) 
> [08:06:46 WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050) 
> [08:06:46 WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363) 
> [08:06:46 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391) 
> [08:06:46 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375) 
> [08:06:46 WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) 
> [08:06:46 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> [08:06:46 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) 
> [08:06:46 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) 
> [08:06:46 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> [08:06:46 WARN]: at java.net.URL.openStream(URL.java:1038) 
> [08:06:46 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130) 
> [08:06:46 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108) 
> [08:06:46 WARN]: at java.lang.Thread.run(Thread.java:745) 
> [08:06:46 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
> [08:06:46 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) 
> [08:06:46 WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
> [08:06:46 WARN]: at sun.security.validator.Validator.validate(Validator.java:260) 
> [08:06:46 WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) 
> [08:06:46 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) 
> [08:06:46 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) 
> [08:06:46 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460) 
> [08:06:46 WARN]: ... 16 more 
> [08:06:46 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
> [08:06:46 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145) 
> [08:06:46 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) 
> [08:06:46 WARN]: at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) 
> [08:06:46 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) 
> [08:06:46 WARN]: ... 22 more 
> [08:06:46 INFO]: [JSONAPI] -------------------------------------
