### ISSUE TITLE
Task #123 ERROR

### ISSUE THREAD

**Issue by AzenoX** [alecgorge/jsonapi#453]
Hi !
I have many task error in my console, I use last version :

[23:23:03 WARN]: [JSONAPI] Task #123 for JSONAPI v5.6.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/en
tity/Player;
        at com.alecgorge.minecraft.jsonapi.streams.PerformanceStreamDataProvider
.run(PerformanceStreamDataProvider.java:23) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java
:53) ~[craftbukkit-1.8.jar:git-Bukkit-726656b]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:349) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:6
68) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:2
84) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
09) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:517) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by Kushhh** [comment]
Do you use the 1.8 version of JSONAPI 5.6.0 ?

**Comment by AzenoX** [comment]
I don't know, but I changed my plugins (jsonapi too)...But have another task error : http://bukkit.org/threads/jsonapi-v5-6-0-for-1-8-console-error-task-15.378405/ and I use JSONAPI 5.6.0 for 1.8

**Comment by Kushhh** [comment]
bukkit.org forums are dead.
do you use any SDK ? what method do you use ?

**Comment by AzenoX** [comment]
1) Bukkit forums is not dead
2) I don't use SDK
3) I don't touch methods, I've just modify options in config.yml

**Comment by electronicboy** [comment]
Tried deleting methods.json and letting JSONAPI rebuild it?

**Comment by AzenoX** [comment]
It doesn't work : 

My config : 
# API methods on the method-whitelist will be
# able to called without any sort of authentication
method-whitelist:
- getPlayerLimit
- dynmap.getPort
options:
  stream_pusher:
    max_queue_age: 30
    max_queue_length: 500
  startup-delay: 2000
  port: 25569
  ip-whitelist: []
  log-to-console: true
  log-to-file: 'false'
  anyone-can-use-calladmin: true
  use-new-api: false
  adminium-push-enabled: true

My error : 
[00:35:01 WARN]: [JSONAPI] Task #17 for JSONAPI v5.6.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/en
tity/Player;
        at com.alecgorge.minecraft.jsonapi.streams.PerformanceStreamDataProvider
.run(PerformanceStreamDataProvider.java:23) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java
:53) ~[craftbukkit-1.8.jar:git-Bukkit-726656b]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:349) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:6
68) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:2
84) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
09) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:517) [craftbukkit-1.8.jar:git-Bukkit-726656b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by AzenoX** [comment]
I work in localhost, I don't know if is important or not...

**Comment by electronicboy** [comment]
https://ci.alecgorge.com/job/JSONAPI/
Try a dev build, I get a feeling this is #380
