### ISSUE TITLE
error players.ops.names

### ISSUE THREAD

**Issue by thetottygames** [alecgorge/jsonapi#454]
hello I have a problaime with players.ops.names method
log on consol :[02:30:24] [Thread-33/WARN]: Exception in thread "Thread-33" 
[02:30:24] [Thread-33/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/MinecraftServer
[02:30:24] [Thread-33/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONAPI.loadOfflinePlayer(JSONAPI.java:816)
[02:30:24] [Thread-33/WARN]: 	at com.alecgorge.minecraft.jsonapi.stringifier.BukkitStringifier.handle(BukkitStringifier.java:141)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:217)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:214)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:104)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:86)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONObject.toJSONString(JSONObject.java:93)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONValue.toJSONString(JSONValue.java:208)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:91)
[02:30:24] [Thread-33/WARN]: 	at org.json.simpleForBukkit.JSONArray.toJSONString(JSONArray.java:98)
[02:30:24] [Thread-33/WARN]: 	at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.call(APIv2Handler.java:86)
[02:30:24] [Thread-33/WARN]: 	at com.alecgorge.minecraft.jsonapi.api.v2.APIv2Handler.serve(APIv2Handler.java:51)
[02:30:24] [Thread-33/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.serve(JSONServer.java:257)
[02:30:24] [Thread-33/WARN]: 	at com.alecgorge.minecraft.jsonapi.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:553)
[02:30:24] [Thread-33/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:30:24] [Thread-33/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.MinecraftServer
[02:30:24] [Thread-33/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[02:30:24] [Thread-33/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[02:30:24] [Thread-33/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:30:24] [Thread-33/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:30:24] [Thread-33/WARN]: 	... 16 more

**Comment by electronicboy** [comment]
Wrong version of the plugin for your server, you're using a 1.7.9 version of jsonapi which isn't compatible with the server you're running.

**Comment by thetottygames** [comment]
Okay  thank you
