### ISSUE TITLE
JSONAPI Crash 1.7.10

### ISSUE THREAD

**Issue by BoolyBoys** [alecgorge/jsonapi#464]
Plateforme : Spigot
Version : 1.7.10 Moddé
Plugin : JSONAPI
Error : I've some error and crash with JSONAPI
Search : Google, forum, spigot, log

Logs console :

[spoiler]

[17:52:47] [Thread-8508/WARN]: java.lang.NoSuchFieldException: length
[17:52:47] [Thread-8508/WARN]: at java.lang.Class.getDeclaredField(Class.java:1953)
[17:52:47] [Thread-8508/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[17:52:47] [Thread-8508/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
[17:52:47] [Thread-8508/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[17:52:47] [Thread-8508/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:52:47] [Thread-8508/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[17:52:47] [Thread-8508/WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[17:52:47] [Thread-8508/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[17:52:47] [Thread-8508/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[17:52:47] [Thread-8508/WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[17:52:47] [Server thread/INFO]: ItsSweaZz issued server command: /f f T0NARD0
[17:52:47] [Server thread/INFO]: [PLAYER_COMMAND] ItsSweaZz: /f f T0NARD0
[17:52:47] [User Authenticator #2094/INFO]: UUID of player _Mob111lol_ is 1eef115f-ea89-3851-a87d-26d76746cdd6
[17:52:47] [Server thread/INFO]: _Mob111lol_[/90.62.124.215:62907] logged in with entity id 4187206 at ([world] -595.4809681292296, 74.0, 454.40438045849334)
[17:52:47] [Server thread/INFO]: [0;32;1m>> [0;37;22m_Mob111lol_[m
[17:52:47] [Server thread/INFO]: Swyrox issued server command: /f claim
[17:52:47] [Server thread/INFO]: [PLAYER_COMMAND] Swyrox: /f claim
[17:52:48] [Server thread/INFO]: darkstart issued server command: /eat
[17:52:48] [Server thread/INFO]: [** Belgique] [Azurixien] VirusAJ >> modo ?
[17:52:49] [Thread-8510/WARN]: java.lang.NoSuchFieldException: length
[17:52:49] [Thread-8510/WARN]: at java.lang.Class.getDeclaredField(Class.java:1953)
[17:52:49] [Thread-8510/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[17:52:49] [Thread-8510/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
[17:52:49] [Thread-8510/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[17:52:49] [Thread-8510/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:52:49] [Thread-8510/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[17:52:49] [Thread-8510/WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[17:52:49] [Thread-8510/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[17:52:49] [Thread-8510/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[17:52:49] [Thread-8510/WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[17:52:49] [Thread-8512/WARN]: java.lang.NoSuchFieldException: length
[17:52:49] [Thread-8512/WARN]: at java.lang.Class.getDeclaredField(Class.java:1953)
[17:52:49] [Thread-8512/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[17:52:49] [Thread-8512/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
[17:52:49] [Thread-8512/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[17:52:49] [Thread-8512/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:52:49] [Thread-8512/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[17:52:49] [Thread-8512/WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[17:52:49] [Thread-8512/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[17:52:49] [Thread-8512/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[17:52:49] [Thread-8512/WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[17:52:49] [Server thread/INFO]: [AuthMe] xXfightPvPXx logged in!
[17:52:49] [Server thread/INFO]: theo24 issued server command: /tpa iSwonnPvP
[17:52:49] [Server thread/INFO]: tino56200 issued server command: /kit
[17:52:49] [Server thread/INFO]: [FearLess] [Azurixien] ichibabette >> modo ou admin
[17:52:49] [Server thread/INFO]: Flojo issued server command: /f kick Kaneki
[17:52:49] [Server thread/INFO]: [Factions v1.6.9.5] Flojo kicked Kaneki from the faction: BlackCraby
[17:52:49] [Server thread/INFO]: [PLAYER_COMMAND] Flojo: /f kick Kaneki
[17:52:50] [Server thread/INFO]: [AuthMe] TheGunCrafter logged in!
[17:52:50] [Server thread/INFO]: xXfightPvPXx issued server command: /home
[17:52:50] [Server thread/INFO]: [AuthMe] _Mob111lol_ used the wrong password
[17:52:51] [Thread-8514/WARN]: java.lang.NoSuchFieldException: length
[17:52:51] [Thread-8514/WARN]: at java.lang.Class.getDeclaredField(Class.java:1953)
[17:52:51] [Thread-8514/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[17:52:51] [Thread-8514/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
[17:52:51] [Thread-8514/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[17:52:51] [Thread-8514/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:52:51] [Thread-8514/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[17:52:51] [Thread-8514/WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[17:52:51] [Thread-8514/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[17:52:51] [Thread-8514/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[17:52:51] [Thread-8514/WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[17:52:51] [Server thread/INFO]: Thedarkfire80 lost connection: Disconnected
[17:52:51] [Server thread/INFO]: << Thedarkfire80
[17:52:51] [Server thread/INFO]: [AuthMe] savain logged in!
[17:52:52] [Server thread/INFO]: Criyzix issued server command: /call oze
[17:52:52] [Server thread/INFO]: [AuthMe] KraKenzZ logged in!
[17:52:53] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking block entity
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-factions.jar:git-Spigot-unknown]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:115) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:98) ~[spigot-factions.jar:git-Spigot-unknown]
at com.alecgorge.minecraft.jsonapi.adminium.Adminium3.sendNotification(Adminium3.java:98) ~[?:?]
at com.alecgorge.minecraft.jsonapi.adminium.Adminium3.pushNotification(Adminium3.java:65) ~[?:?]
at com.alecgorge.minecraft.jsonapi.adminium.Adminium3$ConsoleHandler.publish(Adminium3.java:185) ~[?:?]
at java.util.logging.Logger.log(Logger.java:616) ~[?:1.7.0_79]
at java.util.logging.Logger.doLog(Logger.java:641) ~[?:1.7.0_79]
at java.util.logging.Logger.log(Logger.java:730) ~[?:1.7.0_79]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.TileEntityBrewingStand.l(TileEntityBrewingStand.java:145) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.TileEntityBrewingStand.h(TileEntityBrewingStand.java:74) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1517) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[spigot-factions.jar:git-Spigot-unknown]
... 4 more
[17:52:53] [Server thread/ERROR]: Cause of unexpected exception was
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:115) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:98) ~[spigot-factions.jar:git-Spigot-unknown]
at com.alecgorge.minecraft.jsonapi.adminium.Adminium3.sendNotification(Adminium3.java:98) ~[?:?]
at com.alecgorge.minecraft.jsonapi.adminium.Adminium3.pushNotification(Adminium3.java:65) ~[?:?]
at com.alecgorge.minecraft.jsonapi.adminium.Adminium3$ConsoleHandler.publish(Adminium3.java:185) ~[?:?]
at java.util.logging.Logger.log(Logger.java:616) ~[?:1.7.0_79]
at java.util.logging.Logger.doLog(Logger.java:641) ~[?:1.7.0_79]
at java.util.logging.Logger.log(Logger.java:730) ~[?:1.7.0_79]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-factions.jar:git-Spigot-unknown]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.TileEntityBrewingStand.l(TileEntityBrewingStand.java:145) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.TileEntityBrewingStand.h(TileEntityBrewingStand.java:74) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1517) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-factions.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-factions.jar:git-Spigot-unknown]
[17:52:53] [Server thread/ERROR]: This crash report has been saved to: /home/factions/./crash-reports/crash-2015-10-18_17.52.53-server.txt
[/spoiler]

Can you help me ?

Thank's in advance  !

**Comment by FeverZ** [comment]
I have me to this problem

**Comment by electronicboy** [comment]
#391
