### ISSUE TITLE
JSONAPI + Adminium

### ISSUE THREAD

**Issue by StalKlim** [alecgorge/jsonapi#474]
Hello, I'm using JSONAPI! Version of my server CraftBukkit version git-Spigot-1.7.9-R0.2-204-g534549b (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) And when using the application Adminium I get the following error, the home page will not work, the rest of the applications are running (in part), what could be wrong? Can you help me? 
JSONAPI for 1.7.9 R0.2
Vault 1.4.1
ProtocolLib v3.6.0-SNAPSHOT

[00:15:21] [Server thread/INFO]: [JSONAPI] Enabling JSONAPI v5.6.0
[00:15:21] [Server thread/INFO]: [JSONAPI] Logging to file: false
[00:15:21] [Server thread/INFO]: [JSONAPI] Logging to console: true
[00:15:21] [Server thread/INFO]: [JSONAPI] IP Whitelist = 93.157.211.49,
[00:15:21] [Server thread/INFO]: [JSONAPI] Loaded methods.json.
[00:15:21] [Thread-15/INFO]: [JSONAPI] Waiting 2.000 seconds to load methods so that all the other plugins load...
[00:15:21] [Thread-15/INFO]: [JSONAPI] Any requests in this time will not work...
[00:15:22] [Server thread/INFO]: [JSONAPI] Attempting to use port 20059

[00:15:23] [Thread-15/INFO]: [JSONAPI] Remote Toolkit cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[00:15:23] [Thread-15/INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[00:15:23] [Thread-15/INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[00:15:23] [Thread-15/INFO]: [JSONAPI] Remote Toolkit methods cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[00:15:23] [Thread-15/INFO]: [JSONAPI] 384 methods loaded in 7 namespaces.
[00:15:23] [Thread-15/INFO]: [JSONAPI] ------[Connection information]-------
[00:15:23] [Thread-15/INFO]: [JSONAPI] JSON Server listening on 20059
[00:15:23] [Thread-15/INFO]: [JSONAPI] JSON Stream Server listening on 20060
[00:15:23] [Thread-15/INFO]: [JSONAPI] JSON WebSocket Stream Server listening on 20061
[00:15:23] [Thread-15/INFO]: [JSONAPI] Active and listening for requests.
[00:15:24] [Thread-15/INFO]: [JSONAPI] External IP: 176.31.117.103
[00:15:24] [Thread-15/INFO]: [JSONAPI] Port 20059 is properly forwarded and is externally accessible.
[00:15:24] [Thread-15/INFO]: [JSONAPI] Port 20060 is properly forwarded and is externally accessible.
[00:15:24] [Thread-15/INFO]: [JSONAPI] Port 20061 is properly forwarded and is externally accessible.
[00:15:24] [Thread-15/INFO]: [JSONAPI] -------------------------------------

[00:34:49] [Thread-34/INFO]: [JSONAPI] [API Request] StalKlim requested: jsonapi.users.user.permissions(["StalKlim"]){AUTHED, ALLOWED} 
[00:34:52] [Thread-35/INFO]: [JSONAPI] [API Request] StalKlim requested: jsonapi.users.user.permissions(["StalKlim"]){AUTHED, ALLOWED} plugins.name.version(["JSONAPI"]){AUTHED, ALLOWED} adminium.devices.register(["7fc9bebd55e2f315dc15640b7c9f4c33b6e2283398e8339800b8196627ad0826"]){AUTHED, ALLOWED} 
[00:34:52] [Thread-35/INFO]: [JSONAPI] [API Request] StalKlim requested: players.online.count([]){AUTHED, ALLOWED} server.settings.max_players([]){AUTHED, ALLOWED} streams.name.limit(["performance",150]){AUTHED, ALLOWED} server.version([]){AUTHED, ALLOWED} 
[00:34:52] [Thread-35/WARN]: java.lang.NoSuchFieldException: length
[00:34:52] [Thread-35/WARN]: at java.lang.Class.getDeclaredField(Unknown Source)
[00:34:52] [Thread-35/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:91)
[00:34:52] [Thread-35/WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:91)
[00:34:52] [Thread-35/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftFuture.run(CraftFuture.java:89)
[00:34:52] [Thread-35/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[00:34:52] [Thread-35/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[00:34:52] [Thread-35/WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[00:34:52] [Thread-35/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[00:34:52] [Thread-35/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[00:34:52] [Thread-35/WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by Bencor29** [comment]
UP! I have the same problem !
