### ISSUE TITLE
Error in 1.9 spigot

### ISSUE THREAD

**Issue by Culvanen** [alecgorge/jsonapi#480]
02.03 18:54:43 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
02.03 18:54:43 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
02.03 18:54:43 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
02.03 18:54:43 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
02.03 18:54:43 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
02.03 18:54:43 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot-stb19.jar:git-Spigot-604e046-69e196f]
02.03 18:54:43 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-stb19.jar:git-Spigot-604e046-69e196f]
02.03 18:54:43 [Server] INFO at com.alecgorge.minecraft.jsonapi.streams.PerformanceStreamDataProvider.run(PerformanceStreamDataProvider.java:23) ~[?:?]
02.03 18:54:43 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
02.03 18:54:43 [Server] WARN Task #57 for JSONAPI v5.6.0 generated an exception

**Comment by Alvaroctal** [comment]
[16:15:40] [Thread-26/INFO]: [JSONAPI] Waiting 2.000 seconds to load methods so that all the other plugins load...
[16:15:40] [Thread-26/INFO]: [JSONAPI] Any requests in this time will not work...
[16:15:42] [Thread-26/INFO]: [JSONAPI] Remote Toolkit cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[16:15:42] [Thread-26/INFO]: [JSONAPI] Remote Toolkit methods cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[16:15:42] [Thread-26/INFO]: [JSONAPI] 388 methods loaded in 8 namespaces.
[16:15:42] [Thread-26/INFO]: [JSONAPI] ------[Connection information]-------
[16:15:42] [Thread-26/INFO]: [JSONAPI] JSON Server listening on 20059
[16:15:42] [Thread-26/INFO]: [JSONAPI] JSON Stream Server listening on 20060
[16:15:42] [Thread-26/INFO]: [JSONAPI] JSON WebSocket Stream Server listening on 20061
[16:15:42] [Thread-26/INFO]: [JSONAPI] Active and listening for requests.
[16:15:42] [Thread-26/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:301)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:871)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
[16:15:42] [Thread-26/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[16:15:42] [Thread-26/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[16:15:42] [Thread-26/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
[16:15:42] [Thread-26/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
[16:15:42] [Thread-26/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[16:15:42] [Thread-26/WARN]: 	at java.net.URL.openStream(URL.java:1038)
[16:15:42] [Thread-26/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:131)
[16:15:42] [Thread-26/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:109)
[16:15:42] [Thread-26/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:15:42] [Thread-26/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[16:15:42] [Thread-26/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[16:15:42] [Thread-26/WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[16:15:42] [Thread-26/WARN]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[16:15:42] [Thread-26/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1453)
[16:15:42] [Thread-26/WARN]: 	... 16 more
[16:15:42] [Thread-26/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[16:15:42] [Thread-26/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[16:15:42] [Thread-26/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[16:15:42] [Thread-26/WARN]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[16:15:42] [Thread-26/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[16:15:42] [Thread-26/WARN]: 	... 22 more
[16:15:42] [Thread-26/INFO]: [JSONAPI] -------------------------------------

**Comment by Culvanen** [comment]
UP !

**Comment by elstringer** [comment]
Up

**Comment by xkitox** [comment]
I'm having the same issue.  I was using this for the Adminium app.  Does anyone know another app that works like Adminium to monitor your server on the mobil device?

**Comment by Darunia18** [comment]
@xkitox I have one that works really well, but it's only available for Android. You can find the plugin at http://dev.bukkit.org/bukkit-plugins/bukkit-remote-controller/ and a link to download the app there as well. If you're running Spigot 1.9, you'll have to use the SpecialSouce-2.jar to update it and allow it to work.

**Comment by xkitox** [comment]
@Darunia18 Thanks but I only have iPhone =/

**Comment by alecgorge** [comment]
Try one of these builds. It has updates/fixes for 1.9.* and 1.10.* https://ci.alecgorge.com/job/JSONAPI/lastSuccessfulBuild/artifact/builds/Spigot-all/
