### ISSUE TITLE
Cannot load JSONAPI

### ISSUE THREAD

**Issue by TheKillHDmc** [alecgorge/jsonapi#498]
hello,

Can you help me please ?

[00:19:10] [Server thread/INFO]: [JSONAPI] Enabling JSONAPI v5.6.0
[00:19:10] [Server thread/INFO]: [JSONAPI] Logging to file: false
[00:19:10] [Server thread/INFO]: [JSONAPI] Logging to console: true
[00:19:10] [Server thread/INFO]: [JSONAPI] IP Whitelist = None, all requests are allowed.
[00:19:10] [Server thread/INFO]: [JSONAPI] Loaded methods.json.
[00:19:10] [Thread-27/INFO]: [JSONAPI] Waiting 2.000 seconds to load methods so that all the other plugins load...
[00:19:10] [Thread-27/INFO]: [JSONAPI] Any requests in this time will not work...
[00:19:10] [Server thread/INFO]: [JSONAPI] Attempting to use port 25555
[00:19:10] [Server thread/ERROR]: Error occurred while enabling JSONAPI v5.6.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.alecgorge.minecraft.jsonapi.JSONWebSocketServer.start()V
	at com.alecgorge.minecraft.jsonapi.JSONAPI.onEnable(JSONAPI.java:546) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
[00:19:10] [Server thread/INFO]: [JSONAPI] Disabling JSONAPI v5.6.0
[00:19:10] [Server thread/ERROR]: Error occurred while disabling JSONAPI v5.6.0 (Is it up to date?)
java.lang.NullPointerException
	at com.alecgorge.minecraft.jsonapi.JSONAPI.onDisable(JSONAPI.java:832) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

------------------------------

[00:19:12] [Thread-27/INFO]: [JSONAPI] Remote Toolkit cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[00:19:12] [Thread-27/INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[00:19:12] [Thread-27/INFO]: [JSONAPI] Dynmap cannot be loaded because it depends on a plugin that is not installed: 'dynmap'
[00:19:12] [Thread-27/INFO]: [JSONAPI] Remote Toolkit methods cannot be loaded because it depends on a plugin that is not installed: 'RemoteToolkitPlugin'
[00:19:12] [Thread-27/INFO]: [JSONAPI] 384 methods loaded in 7 namespaces.
[00:19:12] [Thread-27/INFO]: [JSONAPI] ------[Connection information]-------
[00:19:12] [Thread-27/INFO]: [JSONAPI] JSON Server listening on 25555
[00:19:12] [Thread-27/INFO]: [JSONAPI] JSON Stream Server listening on 25556
[00:19:12] [Thread-27/INFO]: [JSONAPI] JSON WebSocket Stream Server listening on 25557
[00:19:12] [Thread-27/INFO]: [JSONAPI] Active and listening for requests.
[00:19:13] [Thread-27/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[00:19:13] [Thread-27/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[00:19:13] [Thread-27/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[00:19:13] [Thread-27/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[00:19:13] [Thread-27/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[00:19:13] [Thread-27/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[00:19:13] [Thread-27/WARN]: 	at java.net.URL.openStream(URL.java:1045)
[00:19:13] [Thread-27/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:130)
[00:19:13] [Thread-27/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:108)
[00:19:13] [Thread-27/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:19:13] [Thread-27/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[00:19:13] [Thread-27/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[00:19:13] [Thread-27/WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[00:19:13] [Thread-27/WARN]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[00:19:13] [Thread-27/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
[00:19:13] [Thread-27/WARN]: 	... 16 more
[00:19:13] [Thread-27/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[00:19:13] [Thread-27/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
[00:19:13] [Thread-27/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[00:19:13] [Thread-27/WARN]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[00:19:13] [Thread-27/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[00:19:13] [Thread-27/WARN]: 	... 22 more
[00:19:13] [Thread-27/INFO]: [JSONAPI] -------------------------------------

**Comment by dartasen** [comment]
You'll need to upgrade your server to at least 1.9.2 to use this build : https://ci.alecgorge.com/job/JSONAPI/134/ 👎
